server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route 1: Cho đường dẫn /auth/**, trỏ đến sys-srv
        - id: auth-service-auth-route
          uri: lb://sys-srv
          predicates:
            - Path=/auth/**

        # Route 2: Cho đường dẫn /users/**, cũng trỏ đến sys-srv
        - id: auth-service-users-route
          uri: lb://sys-srv
          predicates:
            - Path=/users/**

        # Route 2 (MỚI): Cho Medical Record Service
        - id: medical-record-service-route
          uri: lb://medical-record-service
          predicates:
            - Path=/services/**

        # Route 3 (MỚI): Cho Appointment Service
        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
          - Path=/appointments/**

        - id: appointment-service-reviews-route
          uri: lb://appointment-service
          predicates:
            - Path=/reviews/**

        - id: auth-service-branches-route
          uri: lb://sys-srv
          predicates:
            - Path=/branches/**

        - id: product-inventory-service-route
          uri: lb://product-inventory-service
          predicates:
            - Path=/products/**

        - id: product-inventory-service-inventory-route
          uri: lb://product-inventory-service
          predicates:
            - Path=/inventory/**

        - id: medical-record-service-records-route
          uri: lb://medical-record-service
          predicates:
            - Path=/medical-records/**

        - id: medical-record-service-service-material-route
          uri: lb://medical-record-service
          predicates:
            - Path=/service-materials/**

        - id: reporting-service-route
          uri: lb://reporting-service
          predicates:
            - Path=/reports/**

        # Route MỚI: Cho Patient Profiles, cũng trỏ đến sys-srv
        - id: auth-service-profiles-route
          uri: lb://sys-srv
          predicates:
            - Path=/patient-profiles/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka