server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-auth-route
          uri: lb://sys-srv
          predicates:
            - Path=/auth/**

        - id: auth-service-users-route
          uri: lb://sys-srv
          predicates:
            - Path=/users/**

        - id: medical-record-service-route
          uri: lb://medical-record-service
          predicates:
            - Path=/services/**

        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
          - Path=/appointments/**

        - id: appointment-service-reviews-route
          uri: lb://appointment-service
          predicates:
            - Path=/reviews/**

        - id: medical-record-service--protocols-route
          uri: lb://medical-record-service
          predicates:
            - Path=/protocols/**

        - id: auth-service-branches-route
          uri: lb://sys-srv
          predicates:
            - Path=/branches/**

        - id: product-inventory-service-route
          uri: lb://product-inventory-service
          predicates:
            - Path=/products/**

        - id: product-inventory-service-inventory-route
          uri: lb://product-inventory-service
          predicates:
            - Path=/inventory/**

        - id: medical-record-service-records-route
          uri: lb://medical-record-service
          predicates:
            - Path=/medical-records/**

        - id: medical-record-service-service-material-route
          uri: lb://medical-record-service
          predicates:
            - Path=/service-materials/**

        - id: medical-record-service-service-templates
          uri: lb://medical-record-service
          predicates:
            - Path=/templates/**

        - id: reporting-service-route
          uri: lb://reporting-service
          predicates:
            - Path=/reports/**

        - id: auth-service-profiles-route
          uri: lb://sys-srv
          predicates:
            - Path=/patient-profiles/**

        - id: appointment-service-protocol-tracking-route
          uri: lb://appointment-service
          predicates:
            - Path=/protocol-tracking/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: SYS Service
        url: http://localhost:8081/v3/api-docs/sys
      - name: Medical Record Service
        url: http://localhost:8082/v3/api-docs/medical
      - name: Appointment Service
        url: http://localhost:8083/v3/api-docs/appointment
      - name: Product & Inventory Service
        url: http://localhost:8084/v3/api-docs/product
      - name: Reporting Service
        url: http://localhost:8085/v3/api-docs/report

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka